### ISSUE TITLE
2019.08.27-15:00Z | weekly partner meeting

### ISSUE THREAD

**Issue by serapath** [playproject-io/roadmapping#1]
# `location` https://talky.io/play

# AGENDA
1. What was done since last meeting?
    * @ninabreznik
        1. [x] [`roadmapping#11` - 2019.08.23 | attend and present at blockchain week](https://github.com/playproject-io/roadmapping/issues/11)
    * @serapath
        1. [x] [`roadmapping#2` - transition ethereum/play/issues and ethereum-play issues to playproject-io`](https://github.com/playproject-io/roadmapping/issues/2)
        2. [x] [`roadmapping#11` - 2019.08.23 | attend and present at blockchain week](https://github.com/playproject-io/roadmapping/issues/11)
    * @polo13999
    * @fionataeyang
    * @0mkara
    * @shonemik
    * @alincode
    * @ookangzheng
    * @RangerMauve
    * @joshua-mir
2. [How do **roadmapping priorities** currently look like?][1]
3. [Create new meeting and plan what issues we will do until then][2]
    * => **[`2019.09.03-15:00Z#10`](https://github.com/playproject-io/roadmapping/issues/10)**

[1]: https://github.com/playproject-io/roadmapping/blob/master/README.md
[2]: https://github.com/playproject-io/roadmapping/issues/new?template=event.md
