### ISSUE TITLE
roadmapping concept & updates

### ISSUE THREAD

**Issue by serapath** [playproject-io/roadmapping#15]
## `@todo`
* [ ] #32
* [x] ~~delete all files but `README.md`, `.github/` and `LICENSE`~~
* [x] add description
* [ ] #33
* [ ] #9
* [ ] #29 
* [ ] sort roadmapping issues
* [ ] define process of outsourcing tasks and how to pay for it
    * [ ] How to earn if you areca middle man (affiliation) - brainstorm incenive models
    * [ ] add bounties (first manual outsourcing process, later define automated with smart contracts)
    * [ ] people who want to get paid for working on tasks need to be self employed
    * [ ] we want to outsource tasks to remote working self employed individuals and pay for it
    * [ ] initially we might have contractors to work 8 - 15 hours per week until we switch to pure task based
    * [ ] we integrate http://github.com/ethereum/financial-tools/
    * [ ] we want to cater easy tasks to beginners who have never worked remote
    * [ ] initially we want to prefer outsourcing paid tasks to self employed individuals from underprivileged backgrounds
        * where the average hourly payment is ~3-5 USD/h and want to at least pay double (6-10 USD/h)
    * [ ] as soon as people are more experienced and want to work more regular, we want to slowly raise compensation to "western levels"
* [ ] standardise github issue format + tooling
    * [ ] check inspiration
        * https://github.com/ipfs/team-mgmt
        * https://github.com/ipfs/team-mgmt/issues/650
        * https://github.com/ipfs/team-mgmt/issues
    * [ ] standardize github issues to describe involved code, libraries, dependencies, repositories, etc..., so that they can be parsed by an algorithm and describe all aspects of an issue
    * [ ] prepare issue template
    * [ ]convert issues into issue template
    * [ ] make concept to derive ROADMAP and SPEC from issues automatically
* [ ] in-browser compatible multi-repo-management tooling concept
    * [ ] and develop a form to interact with standardized issue so that we can make sure to not break the parseability by editing the issue manually (=> essentially github issues become the "backend" for the tool)
    * [ ] develop a library to checkout and parse the issue to be able to setup all code & repo's involved for development to solve the issue
    * **context**
        1. Every development issue is related to code in files in one or more modules (e.g. dependencies).
        2. In order to solve the issue, a developer who wants to contribute needs to clone all involved repositories, solve the issue and commit and push the changes to make a pull request.
    * **goal**
        1. standardize issues to automatically be able to check out and set up all involved code and repositories in a way that a developer can start immediately with solving the issue and knowing where to look.
        2. do (1.) in a way that will work inside a browser, so that it wont be necessary to use the command line
* [ ] show ROADMAP and SPEC on page
* [ ] show a list of all ecosystem modules in alphabetical order on github page
* [ ] create organisation page module for https://playproject-io.github.io/roadmapping/ to display project management
* [ ] add convenience editor to consistently add/edit issues and sync with github issues via API
* [ ] add notifications about upcoming tasks/events
* [ ] sync all github issue etc... activity to file changes in a "backup" repository to have planning under version control in git
* [ ] factor out all code into seperate tool module and make a static page specifying the data in standard format, but using tool module to generate the page
    * `playproject-io/roadmapping` - to contain the tool as a module and to use "dashboard" tool and sync to "roadmapping" repo data, but work on github and/or data
    * `playproject-io/roadmapping` - to contain the backup of all issues, etc... activity in files/folders
        * issues, etc... as "staging area" which is (can be) committed to the "organisation" repo
* [ ] make concept of how to switch data from mono `/organisation` backup repo to a module specific repo folder to make it multi repo rather than mono repo when it comes to issues
* [ ] switch from github accounts to authorise to dat backend
* [ ] `organisation` - introduce and practice using `playproject-io/roadmapping` tool
* [ ] repository management (e.g. bot to replace hackmd?)
    * [ ] add bot to track all stats of play ecosystem contributions (e.g. modules, contributors, PRs, commits, ...)
    * [ ] display activity in ethereum/play repo static page
* [ ] [`roadmapping#20`: make interaction-graph module](https://github.com/playproject-io/roadmapping/issues/20)
* [ ] [`roadmapping#3`: automate devops](https://github.com/playproject-io/roadmapping/issues/3)

---
**check:**
* http://socialcoding.tk
* https://github.com/blockternship
