### ISSUE TITLE
publish/create/display (paid) tasks

### ISSUE THREAD

**Issue by serapath** [playproject-io/roadmapping#16]
## `@todo`
* [ ] publish/create tasks (bounties/gitcoin integration)
* [ ] "incentive" model for 24/7 mentoring on support chat
* [ ] semi-automation of earn-while-you-learn system (smart contracts for merged pull request)
* [ ] dashboard integration (open/closed/paid tasks etc.)
* [ ] [`roadmapping#19`: issues estimation game](https://github.com/playproject-io/roadmapping/issues/19)
* [ ] [`roadmapping#20`: make interaction-graph module](https://github.com/playproject-io/roadmapping/issues/20)

---
* test your knowledge with paid tasks (bounties/gitcoin - either 5$ tasks or real client tasks, always earn while you learn)
* ensure legal compliance
