### ISSUE TITLE
open & maintain legal entity to do business

### ISSUE THREAD

**Issue by serapath** [playproject-io/roadmapping#18]
## `@todo`
* [ ] opening a company integration
* [ ] accounting logic integration
* [ ] add self employment guide in form of a generated workshop

---
* built-in accounting system with automated reporting
* automation of opening a legal entity (ltd?)

> how to open a UK Ltd.?
what rights and duties does a director have?
what taxes to take care of?
what to include in an invoice?
@todo: document the process of paid contributions for self employed people who want to use a UK Ltd. company
