### ISSUE TITLE
transition ethereum/play/issues and ethereum-play issues to playproject-io

### ISSUE THREAD

**Issue by serapath** [playproject-io/roadmapping#2]
## `@todo`
* [x] link all [`ethereum-play events`](https://github.com/ethereum/play/issues?page=2&q=is%3Aissue+is%3Aclosed+label%3Ameeting) to the first [`playproject-io event`](https://github.com/playproject-io/roadmapping/issues/1)
* [x] transition all `ethereum/play/issues` to `playproject-io issues`
    * [x] transition https://github.com/ethereum/play/issues/153 to https://github.com/playproject-io/smartcontract.codes/issues/1
    * [x] transition https://github.com/ethereum/play/issues/152 to https://github.com/playproject-io/smartcontract.codes/issues/2
    * [x] transition https://github.com/ethereum/play/issues/151 to https://github.com/playproject-io/smartcontract.codes/issues/3
    * [x] transition https://github.com/ethereum/play/issues/150 to https://github.com/playproject-io/smartcontract.codes/issues/4
    * [x] transition https://github.com/ethereum/play/issues/149 to https://github.com/playproject-io/scsen/issues/1 to https://github.com/playproject-io/datdot-tcir/issues/1
    * [x] transition https://github.com/ethereum/play/issues/148 to https://github.com/playproject-io/play-ed/issues/1
    * [x] transition https://github.com/ethereum/play/issues/147 to https://github.com/playproject-io/playproject-io.github.io/issues/1
    * [x] transition https://github.com/ethereum/play/issues/146 to https://github.com/playproject-io/smartcontract-ui/issues/3
    * [x] transition https://github.com/ethereum/play/issues/144 to https://github.com/playproject-io/playproject-io.github.io/issues/2
    * [x] transition https://github.com/ethereum/play/issues/52 to
        * https://github.com/playproject-io/playproject-io.github.io/issues/2
        * https://github.com/playproject-io/smartcontract.codes/issues/5
        * https://github.com/playproject-io/play-ed/issues/3
    * [x] transition https://github.com/ethereum/play/issues/16 to https://github.com/playproject-io/play-ed/issues/4
    * [x] transition https://github.com/ethereum/play/issues/68 to https://github.com/playproject-io/roadmapping/issues/3
    * [x] transition https://github.com/ethereum/play/issues/59 to https://github.com/playproject-io/roadmapping/issues/3
    * [x] transition https://github.com/ethereum/play/issues/1 to https://github.com/playproject-io/roadmapping/issues/4
    * [x] transition https://github.com/ethereum/play/issues/50 to https://github.com/playproject-io/play-ed/issues/2
    * [x] transition https://github.com/ethereum/play/issues/131 to https://github.com/playproject-io/roadmapping/issues/4
    * [x] transition https://github.com/ethereum/play/issues/10 to https://github.com/playproject-io/roadmapping/issues/4
    * [x] transition https://github.com/ethereum/play/issues/143 to https://github.com/playproject-io/scsen/issues/2
    * [x] transition https://github.com/ethereum-play/etherscan-scraper/issues/4 to https://github.com/playproject-io/scsen/issues/3
    * [x] transition https://github.com/ethereum-play/etherscan-scraper/issues/6 to https://github.com/playproject-io/scsen/issues/1
    * [x] transition https://github.com/ethereum-play/etherscan-scraper/issues/8 to https://github.com/playproject-io/scsen/issues/4
    * [x] transition https://github.com/ethereum/play/issues/132 to https://github.com/playproject-io/scsen/issues/1
    * [x] transition https://github.com/ethereum-play/etherscan-scraper/issues/5 to https://github.com/playproject-io/scsen/issues/5
    * [x] transition https://github.com/ethereum-play/etherscan-scraper/issues/9 to https://github.com/playproject-io/solverify/issues/1 to https://github.com/playproject-io-archive/solverify/issues/1
    * [x] transition https://github.com/ethereum-play/etherscan-scraper/issues/7 to https://github.com/playproject-io/scsen/issues/6
    * [x] transition https://github.com/ethereum/play/issues/142 to https://github.com/playproject-io/blog/issues/1
    * [x] transition https://github.com/ethereum/play/issues/141 to https://github.com/playproject-io/smartcontract-ui/issues/4
    * [x] transition https://github.com/ethereum/play/issues/139 to https://github.com/playproject-io/smartcontract-ui/issues/5
    * [x] transition https://github.com/ethereum/play/issues/138 to https://github.com/playproject-io/smartcontract-ui/issues/3
    * [x] transition https://github.com/ethereum/play/issues/49 to https://github.com/playproject-io/smartcontract-ui/issues/3
    * [x] transition https://github.com/ethereum/play/issues/86 to https://github.com/playproject-io/smartcontract-ui/issues/2
    * [x] transition https://github.com/ethereum/play/issues/54 to
        * https://github.com/playproject-io/smartcontract-ui/issues/3
        * https://github.com/playproject-io/wallet-simulator/issues/1
    * [x] transition https://github.com/ethereum/play/issues/53 to https://github.com/playproject-io/smartcontract-ui/issues/6
    * [x] transition https://github.com/ethereum/play/issues/137 to https://github.com/playproject-io/playproject-io.github.io/issues/3
    * [x] transition https://github.com/ethereum/play/issues/136 to https://github.com/playproject-io/smartcontract-ui/issues/7
    * [x] transition https://github.com/ethereum/play/issues/135 to https://github.com/playproject-io/solc-js/issues/1 to https://github.com/playproject-io/solc-js-archive/issues/9
    * [x] transition https://github.com/ethereum/play/issues/46 to https://github.com/playproject-io/solc-js/issues/2 to https://github.com/playproject-io/solc-js-archive/issues/1
    * [x] transition https://github.com/ethereum/play/issues/85 to https://github.com/playproject-io/solc-js/issues/3 to https://github.com/playproject-io/solc-js-archive/issues/8
    * [x] transition https://github.com/ethereum/play/issues/84 to
        * https://github.com/playproject-io/play-ed/issues/5
        * https://github.com/playproject-io/solc-js/issues/4 to https://github.com/playproject-io/solc-js-archive/issues/7
    * [x] transition https://github.com/ethereum/play/issues/134 to https://github.com/playproject-io/solc-js/issues/5 to https://github.com/playproject-io/solc-js-archive/issues/6
    * [x] transition https://github.com/ethereum/play/issues/80 to https://github.com/playproject-io/solc-js/issues/6 to https://github.com/playproject-io/solc-js-archive/issues/5
    * [x] transition https://github.com/ethereum/play/issues/78 to https://github.com/playproject-io/solc-js/issues/7 to https://github.com/playproject-io/solc-js-archive/issues/4
    * [x] transition https://github.com/ethereum/play/issues/75 to https://github.com/playproject-io/roadmapping/issues/5
    * [x] transition https://github.com/ethereum/play/issues/72 to https://github.com/playproject-io/play-ed/issues/6
    * [x] transition https://github.com/ethereum/play/issues/76 to https://github.com/playproject-io/solc-js/issues/8 to https://github.com/playproject-io/solc-js-archive/issues/3
    * [x] transition https://github.com/ethereum/play/issues/77 to https://github.com/playproject-io/solc-js/issues/2 to https://github.com/playproject-io/solc-js-archive/issues/1
    * [x] transition https://github.com/ethereum/play/issues/130 to
        * https://github.com/playproject-io/play-ed/issues/7
        * https://github.com/playproject-io/smartcontract.codes/issues/6
    * [x] transition https://github.com/ethereum/play/issues/129 to
        * https://github.com/playproject-io/roadmapping/issues/11
        * https://github.com/playproject-io/roadmapping/issues/12
        * https://github.com/playproject-io/roadmapping/issues/13
        * https://github.com/playproject-io/roadmapping/issues/14
        * https://github.com/playproject-io/roadmapping/issues/6
        * https://github.com/playproject-io/roadmapping/issues/7
        * https://github.com/playproject-io/roadmapping/issues/8
    * [x] transition https://github.com/ethereum/play/issues/128 to https://github.com/playproject-io/generate-workshop/issues/1
    * [x] transition https://github.com/ethereum/play/issues/127 to https://github.com/playproject-io/generate-workshop/issues/3
    * [x] transition https://github.com/ethereum/play/issues/126 to https://github.com/playproject-io/solc-js/issues/9 to https://github.com/playproject-io/solc-js-archive/issues/2
    * [x] transition https://github.com/ethereum/play/issues/125 to https://github.com/playproject-io/playproject-io.github.io/issues/4
    * [x] transition https://github.com/ethereum/play/issues/57 to https://github.com/playproject-io/roadmapping/issues/15
    * [x] transition https://github.com/ethereum/play/issues/120 to https://github.com/playproject-io/roadmapping/issues/15
    * [x] transition https://github.com/ethereum/play/issues/107 to https://github.com/playproject-io/play-ed/issues/8
    * [x] transition https://github.com/ethereum/play/issues/106 to https://github.com/playproject-io/roadmapping/issues/16
    * [x] transition https://github.com/ethereum/play/issues/105 to https://github.com/playproject-io/roadmapping/issues/16
    * [x] transition https://github.com/ethereum/play/issues/104 to https://github.com/playproject-io/play-ed/issues/9
    * [x] transition https://github.com/ethereum/play/issues/103 to https://github.com/playproject-io/play-ed/issues/10
    * [x] transition https://github.com/ethereum/play/issues/99 to https://github.com/playproject-io/roadmapping/issues/17
    * [x] transition https://github.com/ethereum/play/issues/98 to https://github.com/playproject-io/roadmapping/blob/master/README.md
    * [x] transition https://github.com/ethereum/play/issues/97 to https://github.com/playproject-io/roadmapping/issues/15
    * [x] transition https://github.com/ethereum/play/issues/96 to https://github.com/playproject-io/play-ed/issues/4
    * [x] transition https://github.com/ethereum/play/issues/95 to https://github.com/playproject-io/play-ed/issues/2
    * [x] transition https://github.com/ethereum/play/issues/94 to https://github.com/playproject-io/generate-workshop/issues/2
    * [x] transition https://github.com/ethereum/play/issues/93 to https://github.com/playproject-io/generate-workshop/issues/2
    * [x] transition https://github.com/ethereum/play/issues/92 to https://github.com/playproject-io/roadmapping/issues/16
    * [x] transition https://github.com/ethereum/play/issues/91 to https://github.com/playproject-io/roadmapping/issues/18
    * [x] transition https://github.com/ethereum/play/issues/90 to https://github.com/playproject-io/roadmapping/issues/18
    * [x] transition https://github.com/ethereum/play/issues/89 to https://github.com/playproject-io/roadmapping/issues/18
    * [x] transition https://github.com/ethereum/play/issues/87 to https://github.com/playproject-io/roadmapping/issues/15
    * [x] transition https://github.com/ethereum/play/issues/88 to https://github.com/playproject-io/roadmapping/issues/15
    * [x] transition https://github.com/ethereum/play/issues/83 to https://github.com/playproject-io/wallet-data/issues/1
    * [x] transition https://github.com/ethereum/play/issues/65 to https://github.com/playproject-io/wallet-data/issues/1
    * [x] transition https://github.com/ethereum/play/issues/56 to https://github.com/playproject-io/roadmapping/issues/20
    * [x] transition https://github.com/ethereum/play/issues/55 to https://github.com/playproject-io/generate-workshop/issues/1
    * [x] transition https://github.com/ethereum/play/issues/64 to https://github.com/playproject-io/generate-workshop/issues/1
    * [x] transition https://github.com/ethereum/play/issues/70 to https://github.com/playproject-io/roadmapping/issues/21
    * [x] transition https://github.com/ethereum/play/issues/67 to
        * https://github.com/playproject-io/play-ed/issues/2
        * https://github.com/playproject-io/smartcontract-ui/issues/3
    * [x] transition https://github.com/ethereum/play/issues/66 to https://github.com/playproject-io/play-ed/issues/11
    * [x] transition https://github.com/ethereum/play/issues/62 to https://github.com/playproject-io/smartcontract-ui/issues/9
    * [x] transition https://github.com/ethereum/play/issues/61 to
        * https://github.com/playproject-io/smartcontract.codes/issues/6
        * https://github.com/playproject-io/play-ed/issues/2
    * [x] transition https://github.com/ethereum/play/issues/51 to https://github.com/playproject-io/play-ed/issues/12
    * [x] transition https://github.com/ethereum/play/issues/47 to https://github.com/playproject-io/play-ed/issues/9
    * [x] transition https://github.com/ethereum/play/issues/41 to https://github.com/playproject-io/roadmapping/issues/4
    * [x] transition https://github.com/ethereum-play/workshop-fitbit-dapp/issues/1 to https://github.com/playproject-io/roadmapping/issues/24
    * [x] transition https://github.com/ethereum/play/issues/35 to https://github.com/playproject-io/roadmapping/issues/24
    * [x] transition https://github.com/ethereum/play/issues/22 to https://github.com/playproject-io/roadmapping/issues/24
    * [x] transition https://github.com/ethereum/play/issues/23 to https://github.com/playproject-io/roadmapping/issues/24
    * [x] transition https://github.com/ethereum/play/issues/30 to https://github.com/playproject-io/roadmapping/issues/24
    * [x] transition https://github.com/ethereum/play/issues/31 to https://github.com/playproject-io/roadmapping/issues/24
    * [x] transition https://github.com/ethereum/play/issues/32 to https://github.com/playproject-io/roadmapping/issues/24
    * [x] transition https://github.com/ethereum/play/issues/33 to https://github.com/playproject-io/roadmapping/issues/24
    * [x] transition https://github.com/ethereum/play/issues/19 to https://github.com/playproject-io/roadmapping/issues/24
    * [x] transition https://github.com/ethereum/play/issues/45 to https://github.com/playproject-io/playproject-io.github.io/issues/1
    * [x] transition https://github.com/ethereum/play/issues/7 to https://github.com/playproject-io/generate-codecamp/issues/1
    * [x] transition https://github.com/ethereum/play/issues/11 to
        * https://github.com/playproject-io/roadmapping/issues/18
        * https://github.com/playproject-io/roadmapping/issues/15
    * [x] transition https://github.com/ethereum/play/issues/9 to https://github.com/playproject-io/roadmapping/issues/22
    * [x] transition https://github.com/ethereum/play/issues/8 to https://github.com/playproject-io/hosting/issues/1 to https://github.com/wizardamigos/aybabtu/issues/1
    * [x] transition https://github.com/ethereum/play/issues/5 to https://github.com/playproject-io/play-ed/issues/13
    * [x] transition https://github.com/ethereum/play/issues/60 to https://github.com/playproject-io/play-ed/issues/14
---
