### ISSUE TITLE
standardize user feedback

### ISSUE THREAD

**Issue by serapath** [playproject-io/roadmapping#21]
## `@todo`
* [x] add chat integration to apps
* [ ] add report a bug button
* [ ] standardize a way to get in touch with the "supply network" of components/apps/...

---
