### ISSUE TITLE
smart contract workshop (fitbit, oraclize)

### ISSUE THREAD

**Issue by serapath** [playproject-io/roadmapping#24]
## `@todo`
* [x] when the user signs up, the encrypted token should be stored in the contract (it's encrypted and because it's used to get `beginStep` it's now bound to our contract, so nobody else who would copy the encrypted token could use it
* [x] the methods `kill` and `ownerWithdrawal` should be removed
  * [x] because we don't want to replace centralised servers with almighty owners
* [x] for funders, the minimum funding should be bigger than the users signup fee of 0.1
* [x] users should NEVER have to update their steps
  * [x] instead, the frontend should fetch current steps from the fitbit web api to compare it to `beginStep` to show the user his progress
* [x] when the owner closes the round, the contract should now loop over all users and use their fitbit token to get their end steps
  * [x] maybe you also need to save a `beginDate` and then compare the `endDate` to check if the average daily steps were 10.000
  * [x] the user can close the round only once, so calling the method again will not be possible so the contract can never use the encrypted token again to check step data from users
* [x] if possible - this probably expensive transaction to get all steps from all users should be either paid by the funds in the contract or the owner should be re-imbursed for this by taking that amount from the funds
* [x] when users come to the page after the round was closed, they should be able to "withdraw" their funds from the contract to get them into their metamask account
* [x] add ability to set a custom `duration` (like e.g. 5 minutes) when deploying a contract instance, but (by default it's 30 days) => owner should only be allowed to close contest rount AFTER duration is over
* [x] allow `https://alincode.github.io/fitbit-dapp#dev` to show "debug buttons"
    * e.g. beginning of all javascript checks `localStorage.debug = locatin.hash === "#dev"`
    * including a button to load a different "contract address"
* [x] when in `#dev` mode, display a button to change contract instance address, so app loads with different contract
    * similar to `https://ninabreznik.github.io/voting-ethereum-contract/`
    * source code https://github.com/ninabreznik/voting-ethereum-contract/blob/master/src/index.js#L31
* [x] switch the entire contract to `ROPSTEN` test network
* [x] display on website how much time is left until the contest can close
    * e.g. **`steps in the next ${duration} ${unit ="days"} (10.000 steps per day)`**
    * add **`The Fitbit Contest ends in ${ duration - (now - start)} ${unit}`**
* [x] display to owner a button to `"end contest"` (but if duration is not over yet `alert('wait for ' + duration - (now - start))`
- [x] fix:  updateAllUserStep should add userAddr parameter.
* [x] oraclize often out of gas, it is hard to test.
* [x] use public test chain, it need to waiting very long time to get callback
* [x] Oraclize Token Encryption
    * check conversation: https://gitter.im/oraclize/ethereum-api?at=5b929a9e33ebb72e37e29958
    * maybe use oraclize api https://gitter.im/oraclize/ethereum-api?at=5b957e30728ddf028283d25c
    * or convert python to js https://gitter.im/oraclize/ethereum-api?at=5b95a6bb7189ae6fdd9ef85e
* [x] Fitbit: Presentation for distributed health
    * [x] prepare videos/screencasts for learners
    * [x] Can you try to find "test fitbit accounts"? so that learners can sign in and use the dapp?
    * [x] Could you make 1-5 minute screencast videos to explain the topics used in the dapp?
        * [x] fitbit and how to use fitbit api (get token to make requests)
        * [x] use fitbit api to get steps (javascript fetch)
        * [x] use oraclize web api (to encrypt request/token)
        * [x] use web3.js to call contract methods (e.g. send encrypted request token to contract)
        * [x] use oraclize in a solidity contract ("computational query?" and what it can do)
    * [x] people can join the competition, pay the entrance fee & those who actually successfully finish split the funds amognst themselves
    * [x] some sponsors can join and add funds to the pool
* [x] Prepare Fitbit Demo for Remix folks
* [ ] Can you make a PR to update the english "wording" to improve/change some variable or function names and maybe some other text (...maybe code comments, etc...)
* [ ] fix metamask issue https://github.com/alincode/fitbit-dapp/commit/99c23489f62b8edbec775bf5a8e26d6dde5fc24d

---
**RESULT:**
* **[PREVIEW: github.com/alincode/devon4](https://github.com/alincode/devon4)**

---

**It would:**
1. use fitbit's api https://dev.fitbit.com/build/reference/web-api/
2. so fitbit users can "sign up" and stake some "money/tokens" (alternatively a health insurance provider could take a small percentage of peoples monthly insurance payment and stake it)
3. and fitbit users then get personalised fitness challenges
4. ...if people achieved or over achieved those challenges, they get back what they staked OR they get back money from their health insurance provider - essentially making their insurance cheaper
5. ...if people under achieved their staked tokens or part of their monthly insurance fee goes to all the ones who achieved or over achieved :-)

THIS could be the "baseline scenario" and now we could

1. connect to the fitbit API using some kind of oracle provider service thing (and teach people how to use those)
2. build the contract
3. build the frontend (dapp)
4. write some tests
5. maybe figure out a good scenario which can be used for debugging
6. etc....

The result should be presentable in multiple short captured screencasts:
1. The resources we produce should be chunked into parts that are consumable in 5-10 minutes at most for each of the chunks
2. We can then later use those in online workshops (or documentation) for other people to learn it

the above is meant as a theme (or use case) on which we can show all the different aspects ethereum users might need to think of when using the ecosystem + we can come up with a "story line" that presents all of the remix features - and then split the presentation in small individually presentable chunks :-) ...because in the real world, people want to use existing web services and databases to either fetch some data from or write some new data to.

**Links:**
* http://www.oraclize.it/#services
* support chat: https://gitter.im/oraclize/ethereum-api
* http://docs.oraclize.it/#general-concepts-query
* https://gitter.im/oraclize/ethereum-api?at=5b69e0dbc79ebc1ae7be36c3
* https://github.com/oraclize/ethereum-examples/blob/master/solidity/computation-datasource/url-requests/UrlRequests.sol#L43-L51
* https://www.youtube.com/watch?v=v2Skr_m0J2E&feature=youtu.be

To try out:
* https://remix.oraclize.it/#plugintitle=Oraclize&pluginurl=https://remix-plugin.oraclize.it
* https://github.com/oraclize/ethereum-examples/tree/master/solidity

I build a base function for use Integration call api, and Integration dapp.

Good news is work now, even code still ugly.

https://github.com/alincode/devon4

This is the smart contract information page.
https://rinkeby.etherscan.io/address/0x696a92a0d6b36628dc92e32daba92b85df1c5d5c

```
1st line: oraclize callback
2st line: 2st call smart contract callUserAPI method
3st line: oraclize callback
4st line: 1st call smart contract callUserAPI method, it should don't need to pay any ether, because 1st call for free.
5st line: it is created smart contract transaction.
```

Bad news is, it is very unstable in test chain. Even I paid 1 ether, it always out of gas. it should don't need so many gas, it is just so simple smart contract. I asked the oraclize team, I am waiting for the their reply.

the function is correct, because not always happened "out of gas", I can get correct callback sometime.
![oraclize](https://user-images.githubusercontent.com/7610755/44256458-cf54a000-a23b-11e8-8283-2d73e47cab0b.png)

![2018-08-17 16 30 47](https://user-images.githubusercontent.com/7610755/44256163-f2328480-a23a-11e8-893e-8db23afedcb6.png)

![2018-08-17 16 32 21](https://user-images.githubusercontent.com/7610755/44256262-39b91080-a23b-11e8-9717-aa81c7a88e5f.png)

https://github.com/oraclize/ethereum-bridge
https://github.com/oraclize/truffle-starter

![oraclize1](https://user-images.githubusercontent.com/7610755/44564786-8484dc00-a797-11e8-9f62-ff178078d840.png)
![oraclize2](https://user-images.githubusercontent.com/7610755/44564796-8c448080-a797-11e8-986f-ca2136039a9a.png)
![oraclize3](https://user-images.githubusercontent.com/7610755/44564799-949cbb80-a797-11e8-949a-d11581732a24.png)

The goal is to code a dapp (solidity + frontend) that pulls data from a regular web API.
![diagram](https://user-images.githubusercontent.com/1076427/44435494-27770380-a5a8-11e8-814b-5a1b6339d904.png)

## slides
Prepare the slides

To include:

- oraclize price https://github.com/oraclize/ethereum-api/issues/10
- question of privacy (if token is sent over blockchain vs. if all the competition is hosted on centralized server, problem of trust (escrow), problem of transparency (did they pay all contestants?))
- don't replace central server with a smartcontract which has an almighty owner
  - part of workshop: improve concept of contract by thinking through edge cases
    - (e.g. does the contest happen if only one participant signs up?)

### Problem
Lack of trust in NGOs creates problems when trying to raise donations for a cause. With the use of Smart contracts we can make the flow of donations from donors to recipients transparent.

### Cause - example

**DONORS**
Help us promote a healthy lifestyle by incentivizing people to be more active in their daily life. 

**CONTESTANTS**
Win 1.000$ reward for tracking your steps every day for a month. To make it hassle-free for you to get rewarded for staying active, the smart contract automatically syncs your steps from Fitbit. It checks at the end of the month if you hit your step goal every day. If you did, you will receive the full reward, if not, your reward will be reduced by -33$ for every day you didn't manage to hit your goal.
