### ISSUE TITLE
release pre-alpha

### ISSUE THREAD

**Issue by serapath** [playproject-io/roadmapping#27]
## `@todo`
* [x] release pre-alpha of [smartcontract.codes](https://github.com/playproject-io/smartcontract.codes)
* [x] release pre-alpha of [play-ed](https://github.com/playproject-io/play-ed)
* [x] release pre-alpha of [smartcontract-ui](https://github.com/playproject-io/smartcontract-ui)

---
