### ISSUE TITLE
2019.09.17-15:00Z | weekly partner meeting

### ISSUE THREAD

**Issue by serapath** [playproject-io/roadmapping#29]
## `location` https://talky.io/play & https://gitter.im/ethereum/play

# AGENDA
1. What was done since last meeting?
    * @ninabreznik
        1. [ ] learn to use 2-way-communication (`protocol`) for [hyper modular web component development](https://serapath.github.io/workshop-hypermodular-webcomponents/)
        2. [ ] fetch data with hypertrie from our p2p database
        3. [x] meeting with consensys investor
        4. [x] meet with joshua for datdot
        5. [x] interview with car gonzales
        6. [ ] create a list of smartcontract.codes filters
    * @serapath
        1. [ ] [`roadmapping#23` - transition ethereum/play repo and ethereum-play repos to playproject-io](https://github.com/playproject-io/roadmapping/issues/23)
        2. [x] make `play-components` repository and `brand` repository
        3. [x] meeting with consensys investor
        4. [x] meet with joshua for datdot
        5. [x] interview with car gonzales
        6. [ ] external `app connect` standard
        7. [ ] solc compiler bugfix
        8. [x] [`play-ed#15` - Source is lost after page refresh (f5)](https://github.com/playproject-io/play-ed/issues/15)
        9. [x] [`roadmapping#30` - verify smartcontract.codes & playproject.io domains with github](https://github.com/playproject-io/roadmapping/issues/30)
    * @polo13999
        1. [ ] host data with hypertrie for our p2p database
    * @fionataeyang
        1. [ ] learn to use 2-way-communication (`protocol`) for [hyper modular web component development](https://serapath.github.io/workshop-hypermodular-webcomponents/)
        2. [ ] make a component for smartcontract-ui
        3. [ ] create a list of smartcontract.codes filters
    * @0mkara
    * @shonemik
        1. [ ] stay sane :-)
    * @alincode
        1. [x] solc compiler bugfix
    * @ookangzheng
    * @RangerMauve
    * @joshua-mir
        1. [x] meet with joshua for datdot
2. [How do **roadmapping priorities** currently look like?][1]
3. [Create new meeting and plan what issues we will do until then][2]
    * => **[`????.??.??-15:00Z#??`](https://github.com/playproject-io/roadmapping/issues/??)**

[1]: https://github.com/playproject-io/roadmapping/blob/master/README.md
[2]: https://github.com/playproject-io/roadmapping/issues/new?template=event.md
