### ISSUE TITLE
automate devops

### ISSUE THREAD

**Issue by serapath** [playproject-io/roadmapping#3]
## `@todo`
* [ ] concept for devops (tests, CI, releases, ...)
* [ ] archive finished versions from roadmap into comment and link to github releases
* [ ] define browser compatibility standard
* [ ] setup basic testing
* [ ] setup: alpha, beta & stable deployments
* [ ] optimize bundle until eventually switching to `import` https://github.com/browserify/tinyify
* [ ] add semi-automated release process e.g. https://github.com/ethereum/remix/releases
* [ ] community outreach & decentralised social scaling as a standardized regular output
---
