### ISSUE TITLE
org cleanup

### ISSUE THREAD

**Issue by ninabreznik** [playproject-io/roadmapping#32]
## `@todo`
- [ ] [`datdotorg/datdot-ui#233` org restructuring](https://github.com/datdotorg/datdot-ui/issues/233)
  - [x] move datdot to its own org
    - `@output` :package: https://github.com/datdotorg 
    - [x] make a datdotorg repo on playproject-io org and link to the datdotorg
    - [ ] move the rest of datdot related repos to datdotorg
    - [x] make a datdot-ui repo under datdotorg and link to new datdot-ui org
       - `@output` :package: https://github.com/datdot-ui
      - [x] move all the ui elements over to datdot-ui org
  - [x] move smartcontract.codes to its own org
    - `@output` :package: https://github.com/smartcontract-codes
   - [x] make a smartcontract.codes repo on playproject-io org and link to the smartcontract.codes org

---

**Comment by ninabreznik** [comment]
[worklog: org restructuring Apr 2, 2022 ](https://youtu.be/sJysJ03C_I0)

Results:
- https://github.com/datdotorg
- https://github.com/datdot-ui
- https://github.com/smartcontract-codes
