### ISSUE TITLE
future plans

### ISSUE THREAD

**Issue by serapath** [playproject-io/roadmapping#33]
## `@todo`
* [ ] build hyper data wallet
  * `@output` :question: `hyper data wallet` 
* [ ] build wizardamigos e-learning system to teach ppl how to build p2p apps
  * `@input` :question: `hyper data wallet` 
  * `@output` :question: `wizardamigos elearning system` 
* [ ] build discord like gig chat system
  * `@input` :question: `hyper data wallet` 
  * `@input` :question: `wizardamigos elearning system` 
  * `@output` :question: `discord like gig chat system` 
* [ ] buildhyper based email system - maybe partner with telios
  * `@input` :question: `hyper data wallet` 
  * `@input` :question: `discord like gig chat system`
  * `@output` :question: `email management system`
* [ ] buildhyper personal health communication and record management system
  * `@input` :question: `email management system`
  * `@output` :question: `personal health communication and record management system`

---

## `@info`
...
