### ISSUE TITLE
curriculum planning

### ISSUE THREAD

**Issue by serapath** [playproject-io/roadmapping#4]
## `@todo`
* [x] create DEMO play workshop with editor embedded, themed and with solidity resources
* [ ] **collect CONTENT** 
    * collect short videos, articles, etc... which fit together and teach one thing well so they can be used in the first play workshop
* [ ] **publish WORKSHOPS on custom domains**
* [ ] create a working strategy how to keep the curriculum and workshops up to date
* [ ] develop workshop skilltree to support play :-)
    * [ ] e.g. workshop on how to use play workshops and skilltree system
    * [x] e.g. javascript/html/css workshop
    * [ ] e.g. play-editor workshop https://github.com/ethereum-play/workshop-play-editor
    * [ ] e.g. add all basic workshops (requirements) first
    * [ ] [`generate-codecamp#1`: generate-codecamp concept & updates](https://github.com/playproject-io/generate-codecamp/issues/1)
* [ ] Brainstorm about the length of the workshops
  * [ ] first workshops maybe 2h, later longer?
  * [ ] how many lessons in each workshop and how long each lesson
* [ ] Research possible formats
  * [ ] texts/blog posts
  * [ ] podcasts
  * [ ] Youtube (learner can select if he want audio or video format - if this is even possible)
* [ ] develop workshop skilltree for crypto
    * [x] fix [play-workshop](https://github.com/ethereum-play/play-workshop) module and add theme
    * [x] add solidity workshop
    * [ ] update content https://github.com/ninabreznik/learning-solidity
        * [workshop-solidity](https://github.com/ethereum-play/workshop-solidity)
    * [ ] e.g. deploying (main net, test nets, shards)
    * [ ] e.g. web3/ether.js
    * [ ] e.g. metamask or other alternatives
    * [ ] [`roadmapping#24`: smart contract workshop (fitbit, oraclize)](https://github.com/playproject-io/roadmapping/issues/24)
    * [ ] add fitbit-dapp workshop https://github.com/ethereum-play/workshop-fitbit-dapp/issues/1
    * [ ] e.g. add remix workshop https://github.com/ethereum-play/workshop-remix
* [ ] develop workshop skilltree for javascript
    * [ ] INTRO (not practical yet, just about what is coding, what can you expect to do with it, inspiration etc.)
    * [ ] MARKDOWN (write simple markdown) [see example](https://hackmd.io/Kz0G-buwQn-awaXVqXpdLQ?both)

---

1. LISTS:
  * list of resources from education telegram group
https://docs.google.com/spreadsheets/d/1MdEEkeLFFyfP9SlRMHZMlPUq2Ks_H1g0FMrOZ6y942E/edit#gid=0
  *  from ailin 
https://github.com/alincode/ethereum-zero-to-hero
  * (@ mr. rigel) 
https://ethereum.network/learn
   * Github awesome lists
https://www.google.com/search?ei=htd_XOD4G9yFjLsP1qGzyAI&q=github+awesome+list+ethereum&oq=github+awesome+list+ethereum&gs_l=psy-ab.3..33i22i29i30.1296.2439..2590...0.0..0.79.621.9......0....1..gws-wiz.......0i71j0i22i30.poS4d-lH92s

2. UNSORTED:
  * https://coingape.com/how-to-start-working-with-dapp-for-students/
  * https://github.com/miguelmota/solidity-idiosyncrasies
  * https://github.com/ConsenSys/smart-contract-best-practices
  * https://github.com/fivedogit/solidity-baby-steps/tree/master/contracts
  * https://solidity.readthedocs.io/en/v0.4.24/common-patterns.html
  * magicians forum
  * zero knowledge podcast (ana rose)
  * ethereum wiki
  * MIT blockchain
  * reddit ethereum & ethereum/dev
  * design for crypto.com
  * jackson palmer youtube channel
  * crypto news / mastering ethereum
  * antonopulous
  * LOPP.net/bitcoin.html
  * crypto cannon articles
  * weekly newsletter (for blockchain - nina has link)
  * social coding room (KAI-riot) ...livepeer?
  * livepeer
  * crypto zombies
  * https://ethereum-magicians.org/t/education-session-outtakes-list-of-resources/724
  * https://medium.com/crypto-nyc/twelve-reasons-im-bullish-about-ethereum-today-809a234312b2
  * Solidity series YTB: 
https://www.youtube.com/playlist?list=PL16WqdAj66SCOdL6XIFbke-XQg2GW_Avg
  * Building ICO series 
https://www.youtube.com/playlist?list=PLS5SEs8ZftgULF-lbxy-is9x_7mTMHFIN
  * Web3.js series 
https://www.youtube.com/playlist?list=PLS5SEs8ZftgXlCGXNfzKdq7nGBcIaVOdN
  * Creating an ETH token series: 
https://www.youtube.com/playlist?list=PLS5SEs8ZftgWFuKg2wbm_0GLV0Tiy1R-n
  * https://coursetro.com/posts/code/98/Smart-Contracts-and-Decentralized-Apps-101

--- 

**POTENTIAL PARTNERS:** (we should get content from them)
* solidity team
* openZeppelin team
* Remix team
* DAOstack (Israeli on-chain governance/DAO)
* Goerli/Polkadot
* Metamask
* Burner wallet
* CryptoEconomics
* Ethers.js/Web3
* eWasm (Jake - writing contracts in Rust and running them on eWasm test net)
* ChainSafe (ethereum 2.0, goerli, polkadot, parachains, wasm interpreter, grandpa)
* ethereum.js team
* Tabookey (https://medium.com/tabookey/1-800-ethereum-gas-stations-network-for-toll-free-transactions-4bbfc03a0a56)

**inspiration**
![banner](https://user-images.githubusercontent.com/1076427/50076288-8ad51300-01e1-11e9-8240-6c62f8bf914c.png)

---
